# Generated by Django 5.1.1 on 2024-09-05 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niggiball_app', '0002_team_attack_strength_team_defense_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='predicted_outcome',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
